#  docker-compose up --scale cms=3

version: "3.7"
services:
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    volumes:
      - ./docker/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      cms:
        condition: service_started
    ports:
      - 5000:80
      - 8404:8404

  cms:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: www-data
    volumes:
      - ./cms/:/app/cms
    command: uwsgi --http :5000 -w app:app --enable-threads
    environment:
      - FLASK_SQLALCHEMY_DATABASE_URI=postgresql://cms_user:cms_user@pg:5432/cms
      - FLASK_INIT_DATABASE=True
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - "5000"

  redis:
    image: redis:latest
    expose:
      - "6379"
    # ports:
    #   - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  pg:
    image: postgres
    user: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      # - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


########################################################################
# postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}

# export db_host = localhost
# export db_port = 5432
# export db_user = www-data
# export db_password = www-data

  # postgresql_c2c:
  #   image: docker.io/c2corg/c2corg_pgsql:anon-2018-11-02
  #   environment:
  #     PGDATA: '/c2corg_anon'
  #   # volumes:
  #     # - ./docker-compose/pgsql-settings.d/:/c2corg_anon/pgsql-settings.d/
  #   ports:
  #     - 5432:5432

  # pg_ui:
  #   image: dpage/pgadmin4:4.0
  #   depends_on:
  #     - postgresql_c2c
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=password

  #     # do not require auth
  #     - PGADMIN_CONFIG_SERVER_MODE=False
  #     - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
  #   ports:
  #     - 5050:80
