name: Continuous integration

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron:  '00 02 * * 2-6'
  pull_request:
    branches:
      - "**"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install -r requirements.txt -r dev-requirements.txt
    - run: black --check --diff .
    - run: pylint wiki_api tests
    - run: pytest
      env:
        PYTHONPATH: .
